---
collections:

#Default
  - name: awx.awx
  - name: community.vmware
  - name: kubernetes.core
  - name: ansible.posix
  - name: ansible.windows

#IIS
  - name: community.docker
  - name: community.general
  - name: community.windows
  - name: community.hashi_vault